# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 23:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0002_auto_20171117_2321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='referral',
            new_name='referrals',
        ),
    ]
