# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-18 02:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0003_auto_20171117_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='referral',
            name='extrainfo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
